package uy.edu.curso.ejercicio17y18;
import java.util.Comparator;
//PRIMERO QUE NADA, DEFINIMOS LA INTERFAZ TDALista, QUE ES LA QUE VA A DEFINIR LOS MÉTODOS QUE DEBE IMPLEMENTAR CUALQUIER CLASE QUE QUIERA SER UNA LISTA. 
// EN ESTE CASO, VAMOS A IMPLEMENTAR UNA LISTA ENLAZADA, PERO PODRÍAMOS IMPLEMENTAR OTRA ESTRUCTURA DE DATOS COMO UN ARREGLO O UNA PILA, Y TODAS ELLAS DEBERÍAN IMPLEMENTAR ESTA INTERFAZ PARA GARANTIZAR QUE TIENEN LOS MÉTODOS BÁSICOS DE UNA LISTA.
//TDA = Tipo Abstracto de Datos -> es una forma de definir un tipo de dato sin especificar cómo se implementa, solo definiendo qué operaciones se pueden realizar con ese tipo de dato. ES EL "QUE" NO ES "COMO"

interface TDALista<T>  //DEFINIMOS LA INTERFAZ TDALista, QUE ES UNA INTERFAZ GENÉRICA, ES DECIR, QUE PUEDE TRABAJAR CON CUALQUIER TIPO DE DATO (T)
{
    boolean agregar(T elemento); //MÉTODO PARA AGREGAR UN ELEMENTO A LA LISTA, RECIBE UN ELEMENTO DE TIPO T Y DEVUELVE UN BOOLEANO QUE INDICA SI EL ELEMENTO SE AGREGÓ CORRECTAMENTE O NO.
    
    T obtener(int indice); //MÉTODO PARA OBTENER UN ELEMENTO DE LA LISTA, RECIBE UN ÍNDICE Y DEVUELVE EL ELEMENTO QUE SE ENCUENTRA EN ESE ÍNDICE.
    
    T eliminar(int indice); //MÉTODO PARA ELIMINAR UN ELEMENTO DE LA LISTA, RECIBE UN ÍNDICE Y DEVUELVE EL ELEMENTO QUE SE ELIMINÓ.
    
    boolean eliminar(T elemento); //MÉTODO PARA ELIMINAR UN ELEMENTO DE LA LISTA, RECIBE UN ELEMENTO DE TIPO T Y DEVUELVE UN BOOLEANO QUE INDICA SI EL ELEMENTO SE ELIMINÓ CORRECTAMENTE O NO.
    
    int tamaño(); //MÉTODO PARA OBTENER EL TAMAÑO DE LA LISTA.
    
    boolean esVacia(); //MÉTODO PARA VERIFICAR SI LA LISTA ESTÁ VACÍA O NO
        
    void ordenar(Comparator<T> comp); // ← agregar esto

}

